### ISSUE TITLE
3.0 doc elements tracking issue

### ISSUE THREAD

**Issue by aomarks** [PolymerElements/iron-component-page#132]
P0:
- [x] Support demos.
- [x] Deep link scrolling doesn't work when the page is loaded.
- [x] Scrolling is still off for things at the bottom of the page.
- [x] `iron-component-page` should default to `analysis.json`.
- [x] `iron-component-page` should have a `base-href` property that's forwarded to the `iron-doc-viewer` so that you can turn on non-fragment routing.
- [x] `iron-doc-nav` links are no longer highlighted for current path.
- [x] New READMEs.
- [x] Method descriptions are missing.
- [ ] Release 3.0.0.

P1:
- [x] Document that `base-href` must not have trailing slash.
- [x] Top-level namespace has title "Namespace undefined".
- [x] Don't show function param list if none of them have documentation.
- [x] Don't show hamburger menu when in full-width mode, since it doesn't do anything.
- [x] Clicking a link from within the doc viewer doesn't reset scroll.
- [x] Property/function descriptions aren't markdown rendered.
- [x] `scrollIntoView` doesn't take into account our header. Can app-layout help? Maybe scroll to center instead?
- [x] Coming into a deep link should highlight the anchor section for a moment so you know what you're looking for.
- [x] Long titles look bad on mobile.
- [x] Hide empty nav categories.
- [x] Behavior titles don't render.
- [x] Hamburger menu can get squashed by long headings.
- [x] Improve/colorize function signature formatting.
- [x] Content doesn't collapse well when there is a markdown `pre` stretching the viewer width.
- [x] Sort out index.html and demo for these repos. Is the demo of icp just itself?
- [x] Test demos on mobile, iOS
- [x] Better demo listing. Expando.
- [x] Static methods.

P2:
- [ ] Add source links.
- [ ] If there's only one thing in the descriptor, maybe `idv` should just take you to it.
- [x] `icp` tests
- [ ] `viewer` and `nav` should probably do descriptor flattening themselves, not rely on `component-page` to do it.
- [x] General CSS/markup cleanup pass. A bunch of minor formatting bugs. There's some inert code/CSS. Standardizing CSS with webcomponents.org so that less post-transform is needed.
- [ ] polymer-cli automatically generates `analysis.json`.
- [ ] Show a nav entry for the top-level namespace ("global"?).
- [x] Show where an inherited thing was inherited from.
- [ ] If you deep link to a protected thing, the protected box should get auto checked.

**Comment by jsilvermist** [comment]
When looking at an API Reference such as [Polymer.ArraySelector](https://aomarks-test-docs.appspot.com/#/elements/Polymer.ArraySelector) on mobile there's no margin on the right, which is especially noticeable on the `pre` tags with the background touching the edge.

**Comment by aomarks** [comment]
Discussing 3.x final release at https://github.com/PolymerElements/iron-component-page/pull/139. Filed a few other issues for the remaining open items.

**Comment by aomarks** [comment]
Also @jsilvermist the padding issue you mentioned was fixed at some point :)
